# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-04-17 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_officials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legislator',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='legislator',
            name='chamber',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legislator',
            name='email',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legislator',
            name='last_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legislator',
            name='party',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legislator',
            name='phone',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legislator',
            name='pid',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legislator',
            name='state_name',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legislator',
            name='term_end',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='legislator',
            name='term_start',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
