# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-04-17 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_officials', '0002_auto_20170417_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislator',
            name='cid',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='party',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='pid',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='state',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='state_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='term_end',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='term_start',
            field=models.CharField(max_length=30),
        ),
    ]
