# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-04-29 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_officials', '0004_legislator_twitter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislator',
            name='twitter_id',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
