# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-30 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_officials', '0006_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='legislators',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
