# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-31 00:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public_officials', '0010_auto_20170530_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userslegislators',
            name='legislator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to='public_officials.Legislator'),
        ),
        migrations.AlterField(
            model_name='userslegislators',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
