# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-05-31 00:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public_officials', '0011_auto_20170531_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userslegislators',
            name='legislator',
        ),
        migrations.RemoveField(
            model_name='userslegislators',
            name='user',
        ),
        migrations.AddField(
            model_name='legislator',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UsersLegislators',
        ),
    ]
