# -*- coding: utf-8 -*-
# Generated by Django 1.11rc1 on 2017-12-09 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_officials', '0012_auto_20170531_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislator',
            name='state_name',
        ),
        migrations.RemoveField(
            model_name='legislator',
            name='term_end',
        ),
        migrations.RemoveField(
            model_name='legislator',
            name='term_start',
        ),
        migrations.AddField(
            model_name='legislator',
            name='cspan_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='legislator',
            name='google_entity_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='legislator',
            name='govtrack_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='legislator',
            name='in_office',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='legislator',
            name='leadership_role',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='legislator',
            name='url',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='legislator',
            name='votesmart_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='chamber',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='cid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='party',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='pid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='legislator',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
